### ISSUE TITLE
penman.Graph() call not compatible with default install

### ISSUE THREAD

**Issue by goodmami** [aghie/tb-amr#1]
The `install.sh` script installs the latest version of Penman from PyPI, currently at [line 5](https://github.com/aghie/tb-amr/blob/2b9818c5d702955ff0d66ae9b7d82b9347e57cd9/install.sh#L5):

```
pip install pattern stop-words numpy scipy matplotlib prettytable sklearn python-dateutil stop-words penman h5py
```

The latest version is [0.7.2](https://pypi.org/project/Penman/) which changes, among many other things, how `penman.Graph()` is instantiated. [Line 655 of utils.py](https://github.com/aghie/tb-amr/blob/2b9818c5d702955ff0d66ae9b7d82b9347e57cd9/utils.py#L655) uses it like this:

```python
        g = penman.Graph(data=new_triplets, top= top)
```

In the current version, the `data` parameter is renamed `triples`, so this will break. You can either change the parameter name (I *think* this is the only thing broken) or fix your install to be `penman==0.6.2`.

Cheers

**Comment by aghie** [comment]
Thanks a lot!
